version: '3'
services:
  app:
    build: .
    depends_on:
      - db
    volumes:
      - ./:/app
    ports:
      - 3000:3000
  db:
    image: postgres
    volumes:
      - ./tmp/db:/var/lib/postgresql/data